import{alignment,mod4,targetTurn}from'./simulation.js';
export class FlatScene{
 constructor(canvas,onTap){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onTap=onTap;this.clock=0;this.hit=[];new ResizeObserver(()=>this.resize()).observe(canvas);this.resize();let down;canvas.addEventListener('pointerdown',e=>down={id:e.pointerId,x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId||Math.hypot(e.clientX-down.x,e.clientY-down.y)>10)return;down=null;const r=canvas.getBoundingClientRect(),x=e.clientX-r.x,y=e.clientY-r.y;const b=this.hit.find(h=>Math.hypot(h.x-x,h.y-y)<h.r);if(b)this.onTap(b.id,e.shiftKey?-1:1);});}
 resize(){this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;const d=Math.min(devicePixelRatio,2);this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);}
 setView(){}event(){}
 render(s,dt){const c=this.ctx,w=this.w,h=this.h;this.clock+=dt;this.hit=[];c.fillStyle='#072b28';c.fillRect(0,0,w,h);const laneW=Math.min((w-32)/s.lanes,125),left=(w-laneW*s.lanes)/2,top=110,bottom=h-210,len=Math.max(170,bottom-top);
 c.strokeStyle='#19473f';c.lineWidth=1;for(let x=0;x<w;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}
 c.fillStyle='#124e40';c.fillRect(w/2-83,top-85,166,60);c.fillStyle='#cbffc2';c.font='900 14px system-ui';c.textAlign='center';c.fillText('SUJA · LABEL / ROUTE',w/2,top-50);
 for(let lane=0;lane<s.lanes;lane++){const x=left+lane*laneW;c.fillStyle='#45625b';c.fillRect(x+3,top,laneW-6,len);c.strokeStyle='#709788';for(let i=0;i<len;i+=10){c.beginPath();c.moveTo(x+5,top+i);c.lineTo(x+laneW-5,top+i);c.stroke();}c.fillStyle='#b97cff50';c.fillRect(x+3,top+len*.78,laneW-6,len*.2);c.fillStyle='#aff47d';c.fillRect(x+2,top,2,len);c.fillStyle='#c7eac9';c.font='bold 12px system-ui';c.fillText(lane+1,x+laneW/2,bottom+15);}
 c.fillStyle='#103b82';c.fillRect(left-3,bottom+28,laneW*s.lanes+6,110);for(let i=0;i<5;i++){c.fillStyle='#20569e';c.fillRect(left-3,bottom+28+i*21,laneW*s.lanes+6,10);}
 const draw=(x,y,size,turn,color='#d1ad78',target=null)=>{c.save();c.translate(x,y);if(target!==null){c.save();c.rotate(target*Math.PI/2);c.strokeStyle=mod4(turn)===target?'#b9ff81':alignment(turn,target)?'#ffca79':'#bf98fc';c.lineWidth=2;c.setLineDash([5,4]);c.strokeRect(-size*.58,-size*.39,size*1.16,size*.78);c.setLineDash([]);c.restore();}c.rotate(turn*Math.PI/2);c.fillStyle='#755631';c.fillRect(-size*.48,-size*.29+5,size*.96,size*.58);c.fillStyle=color;c.fillRect(-size*.48,-size*.29,size*.96,size*.58);c.fillStyle='#ecd29e';c.fillRect(-size*.05,-size*.29,size*.1,size*.58);c.fillStyle='#0b704f';c.fillRect(-size*.45,size*.05,size*.9,size*.13);c.fillStyle='white';c.fillRect(-size*.2,size*.19,size*.4,size*.12);c.font=`900 ${Math.max(10,size*.17)}px system-ui`;c.textAlign='center';c.fillText('↓',0,size*.01);c.restore();};
 for(let lane=0;lane<s.lanes;lane++)for(let row=0;row<2;row++){const x=left+(lane+.5)*laneW,y=bottom+55+row*43;const slot=s.placed.filter(b=>b.lane===lane&&b.row===row).at(-1);if(slot)draw(x,y,laneW*.8,slot.turn);if(!s.slots.includes(lane+':'+row)){c.save();c.translate(x,y);c.rotate(targetTurn(lane,row,s.lanes)*Math.PI/2);c.strokeStyle='#b7ff74';c.lineWidth=2;c.strokeRect(-laneW*.35,-laneW*.23,laneW*.7,laneW*.46);c.fillStyle='#d6ffad';c.font='bold 18px system-ui';c.fillText('↓',0,6);c.restore();}}
 for(const b of [...s.boxes].sort((a,b)=>a.progress-b.progress)){const x=w/2+(left+(b.lane+.5)*laneW-w/2)*Math.min(1,Math.max(0,(b.progress-.12)/.2)),y=top+b.progress*len;draw(x,y,laneW*.75,b.turn,'#d1ad78',b.target);if(b.progress>=.22)this.hit.unshift({id:b.id,x,y,r:Math.max(27,laneW*.5)});}
 }
}
