import{Stacker,LEVELS,rankRuns,mod4}from'./simulation.js';import{GameScene}from'./scene.js';import{FlatScene}from'./fallback.js';import{Audio}from'./audio.js';import{Community}from'./community.js';
const $=id=>document.getElementById(id),audio=new Audio(),community=new Community();let scene,sim,playing=false,countdown=0,last=0,acc=0,hudClock=0,cueTimer,endTimer,runId,runOwner,pendingResult,saveBusy=false,boardGeneration=0,view=localStorage.getItem('stackerView')||'line';
try{scene=new GameScene($('world'),rotate);}catch(e){console.info('Using compatible renderer',e);const canvas=$('world'),replacement=canvas.cloneNode();canvas.replaceWith(replacement);scene=new FlatScene(replacement,rotate);$('graphics-notice').hidden=false;}
$('retry-graphics').onclick=()=>location.reload();
scene.setView(view);sim=new Stacker({practice:true});
function rotate(id,dir=1){if(!playing||countdown)return;audio.unlock();sim.rotate(id,dir);}
function cue(text,bad=false){clearTimeout(cueTimer);const el=$('cue');el.textContent=text;el.className=bad?'bad':'';el.hidden=false;el.style.animation='none';void el.offsetWidth;el.style.animation='';cueTimer=setTimeout(()=>el.hidden=true,900);}
function onEvent(e){scene.event(e);audio.fx(e.type==='stack'?e.timed?'perfect':e.label?'stack':'label':e.type);if(e.type==='stack')cue(e.timed?`PERFECT! +${e.points}`:e.label?`NICE! +${e.points}`:`LABEL IN · −${e.penalty}`,!e.label);if(e.type==='miss')cue('NEXT CASE. YOU’VE GOT THIS.',true);
 if(e.type==='layer'||e.type==='pallet'){$('milestone').hidden=false;$('milestone-note').textContent=e.type==='pallet'?'PALLET COMPLETE':'LAYER COMPLETE';$('milestone-title').textContent=e.type==='pallet'?['Green light, nailed.','Citrus, stacked.','Full stack champion!'][sim.level]:['Looking sharp!','Stacking strong!','Keep it clean!','One layer to go!'][sim.layer];$('milestone-points').textContent=`+${e.points.toLocaleString()}`;}
 if(e.type==='levelStart')buildLanes();if(e.type==='end'){audio.active=false;endTimer=setTimeout(showResult,900);}
}
function buildLanes(){$('lane-buttons').replaceChildren();for(let i=0;i<sim.lanes;i++){const b=document.createElement('button');b.innerHTML=`<b>${i+1}</b> ↻`;b.title=`Rotate nearest case in lane ${i+1}`;b.setAttribute('aria-label',b.title);b.addEventListener('click',e=>{audio.unlock();if(playing&&!countdown)sim.rotateLane(i,e.shiftKey?-1:1);});$('lane-buttons').append(b);}if(sim.practice)$('lives').textContent='UNLIMITED';}
function update(){if(!playing)return;$('score').textContent=sim.score.toLocaleString();$('combo').textContent=sim.combo?`${sim.combo} CLEAN · ×${sim.multiplier}`:'BUILD YOUR STREAK';$('level').innerHTML=`0${sim.level+1} <small>/ 03</small>`;$('level-name').textContent=sim.config.name;$('layer-note').textContent=`LAYER ${sim.layer+1} / 5 · ${sim.slots.length}/${sim.lanes*2}`;$('lives').textContent=sim.practice?'PRACTICE · UNLIMITED':`${sim.lives} CHANCE${sim.lives===1?'':'S'}`;$('layers').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<sim.layer?'filled':i===sim.layer?'current':''}"></i>`).join('');
 $('milestone').hidden=!['layer','level'].includes(sim.state);for(const [i,b]of [...$('lane-buttons').children].entries()){b.disabled=sim.paused||countdown>0||sim.state!=='playing';b.classList.toggle('near',sim.boxes.some(x=>x.lane===i&&x.progress>=.78));}}
function start(practice=false){clearTimeout(endTimer);clearTimeout(cueTimer);for(const d of document.querySelectorAll('dialog[open]'))d.close();runId=crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');runOwner=community.profile?.profileId||null;pendingResult=null;saveBusy=false;sim=new Stacker({seed:crypto.getRandomValues(new Uint32Array(1))[0],practice,onEvent});playing=true;countdown=3.4;acc=0;audio.unlock();audio.active=false;$('menu').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('lane-controls').hidden=false;$('countdown').hidden=false;$('cue').hidden=true;$('milestone').hidden=true;buildLanes();update();}
function menu(){clearTimeout(endTimer);saveBusy=false;playing=false;audio.active=false;countdown=0;boardGeneration++;for(const d of document.querySelectorAll('dialog[open]'))d.close();for(const id of ['hud','pause','lane-controls','milestone','countdown','cue'])$(id).hidden=true;$('menu').hidden=false;sim=new Stacker({practice:true});}
function pause(){if(!playing||['won','lost'].includes(sim.state)||sim.paused)return;sim.paused=true;audio.active=false;$('pause-dialog').showModal();}
function resume(){sim.paused=false;acc=0;audio.unlock();audio.active=countdown<=0;$('pause-dialog').close();}
function tick(now){requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000||.016);last=now;acc+=dt;while(acc>=1/60){if(playing){if(!sim.paused&&countdown>0){const old=Math.ceil(countdown);countdown=Math.max(0,countdown-1/60);const num=countdown>.4?Math.ceil(countdown-.4):'GO!';$('count-number').textContent=num;if(Math.ceil(countdown)!==old)audio.fx('tick');if(countdown<=0){$('countdown').hidden=true;audio.active=true;}}else if(!countdown)sim.step(1/60);}else{for(const b of sim.boxes)if(b.progress>.7)b.turn=b.target;sim.step(1/60);if(sim.state==='won')sim=new Stacker({practice:true});}acc-=1/60;}audio.step(dt);scene.render(sim,sim.paused?0:dt);hudClock+=dt;if(hudClock>=.08){update();hudClock=0;}}
async function board(listId='board',statusId='board-status'){const gen=++boardGeneration;$(listId).replaceChildren();$(statusId).textContent='Loading crew scores…';try{await community.init();if(!community.profile)throw Error('Sign in at SUJA Game Center to see crew scores.');const [directory,runs,hidden]=await Promise.all([community.read('directory'),community.read('stackerRuns'),community.read('stackerModeration')]);if(gen!==boardGeneration)return;const rows=rankRuns(directory,runs,hidden);$(statusId).textContent=rows.length?'Arcade scores · Highest score wins.':'The first great stack could be yours.';for(const [i,r]of rows.entries()){const li=document.createElement('li'),name=document.createElement('span'),score=document.createElement('b');name.textContent=`${i+1}. ${r.displayName}`;score.textContent=r.score.toLocaleString();li.append(name,score);$(listId).append(li);}}catch(e){if(gen===boardGeneration)$(statusId).textContent=/permission/i.test(String(e))?'Crew scores are awaiting the Pallet Stacker database update.':String(e.message||e);}}
function localSave(result){try{const key='stackerRuns:'+ (runOwner||'guest'),old=JSON.parse(localStorage.getItem(key)||'[]').filter(r=>r.id!==runId);old.push({...result,id:runId,at:Date.now()});localStorage.setItem(key,JSON.stringify(old.sort((a,b)=>b.score-a.score).slice(0,30)));}catch{}}
async function save(){if(!pendingResult||saveBusy)return;saveBusy=true;$('retry-save').hidden=true;const result=pendingResult,id=runId,owner=runOwner;try{await community.init();if(community.profile?.profileId!==owner||!owner)throw Error('Sign in with the player who started this run to save it.');const path=`stackerRuns/${owner}/${id}`;const existing=await community.read(path);if(!existing)await community.write(path,{...result,displayName:community.profile.displayName,finishedAt:community.api.serverTimestamp()});if(runId===id){pendingResult=null;$('save-status').textContent='Saved to your SUJA player card.';board();}}catch(e){if(runId===id){$('save-status').textContent=/permission/i.test(String(e))?'Saved on this device. Crew saving needs the Pallet Stacker database rules update.':`Saved on this device. ${e.message||'Connection unavailable.'}`;$('retry-save').hidden=false;}}finally{if(runId===id)saveBusy=false;}}
function showResult(){const result=sim.result();$('milestone').hidden=true;$('result-note').textContent=sim.practice?'PRACTICE COMPLETE':sim.state==='won'?'THREE PALLETS. ONE CHAMPION.':'SHIFT COMPLETE';$('result-title').textContent=sim.state==='won'?'That’s a full stack.':'Ready for a rematch?';$('result-score').textContent=result.score.toLocaleString();$('stats').replaceChildren();for(const [value,label]of [[result.stacked,'CASES STACKED'],[result.perfect,'PERFECT TURNS'],[result.completed+'/3','PALLETS'],[result.labels,'LABELS OUT'],[result.maxCombo,'BEST STREAK'],[Math.round(result.duration)+'s','ACTIVE TIME']]){const div=document.createElement('div'),b=document.createElement('b'),span=document.createElement('span');b.textContent=value;span.textContent=label;div.append(b,span);$('stats').append(div);}localSave(result);$('retry-save').hidden=true;$('save-status').textContent=sim.practice?'Practice stays on this device.':runOwner?'Saving your run…':'Saved on this device. Sign in at Game Center before your next run for crew scores.';$('results').showModal();board();if(!sim.practice&&runOwner){pendingResult=result;save();}}
$('start').onclick=()=>start();$('practice').onclick=()=>start(true);$('again').onclick=()=>start(sim.practice);$('result-menu').onclick=menu;$('brand').onclick=e=>{e.preventDefault();if(playing)pause();};$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=menu;$('how').onclick=()=>$('help').showModal();$('scores').onclick=()=>{$('board-dialog').showModal();board('menu-board','menu-board-status');};$('retry-save').onclick=save;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('results').addEventListener('cancel',e=>{e.preventDefault();menu();});
$('sound').setAttribute('aria-pressed',String(audio.on));$('sound').onclick=()=>{$('sound').setAttribute('aria-pressed',String(audio.toggle()));$('sound').textContent=audio.on?'♫':'♪';};$('camera').onclick=()=>{view={line:'angle',angle:'overhead',overhead:'line'}[view]||'line';scene.setView(view);localStorage.setItem('stackerView',view);};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='Escape'&&playing){e.preventDefault();if(sim.paused)resume();else pause();}if(!playing||countdown||sim.paused||document.querySelector('dialog[open]'))return;const key=e.code.match(/^(?:Digit|Numpad)([1-5])$/);if(key&&!e.repeat){e.preventDefault();audio.unlock();sim.rotateLane(Number(key[1])-1,e.shiftKey?-1:1);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});community.subscribe(p=>{$('player').textContent=p?`Playing as ${p.displayName} · SUJA crew`:'Guest play · Sign in at Game Center to save crew scores.';});community.init().catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});requestAnimationFrame(tick);
