import * as T from 'three';import{M,box,sign,caseModel,outline,pallet,mat}from'./models.js';import{mod4,alignment,targetTurn}from'./simulation.js';
export const laneX=(lane,lanes)=>(lane-(lanes-1)/2)*1.85;
export const pathPosition=(b,lanes)=>{const split=T.MathUtils.smoothstep(b.progress,.12,.32);return new T.Vector3(laneX(b.lane,lanes)*split,1.64,-12+b.progress*17);};
export class GameScene{
 constructor(canvas,onTap){this.canvas=canvas;this.onTap=onTap;this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.3;this.scene=new T.Scene();this.scene.background=new T.Color(0x082a28);this.scene.fog=new T.Fog(0x082a28,32,65);this.camera=new T.OrthographicCamera(-10,10,10,-10,.1,90);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.live=new Map();this.placed=[];this.flights=[];this.fx=[];this.clock=0;this.view='line';this.template=caseModel();this.level=-1;
 this.scene.add(new T.HemisphereLight(0xc8ffe8,0x163c41,2.8));const sun=new T.DirectionalLight(0xffe3b1,4.2);sun.position.set(-9,20,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:17,top:19,bottom:-19,near:.5,far:50});sun.shadow.normalBias=.035;this.scene.add(sun);const fill=new T.DirectionalLight(0xb896ff,3);fill.position.set(10,8,-5);this.scene.add(fill);
 this.world();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.resize();let down;
 canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,id:e.pointerId};});canvas.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId||Math.hypot(e.clientX-down.x,e.clientY-down.y)>10){down=null;return;}down=null;const id=this.pick(e.clientX,e.clientY);if(id)this.onTap(id,e.shiftKey?-1:1);});canvas.addEventListener('pointercancel',()=>down=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());
 }
 world(){this.scene.add(box(65,.2,70,M.floor,0,-3,0));const grid=new T.GridHelper(60,30,0x337c65,0x224c48);grid.position.y=-2.89;this.scene.add(grid);
 const wall=mat(0x0b4237,.8);this.scene.add(box(55,20,.4,wall,0,6,-21));for(let x=-24;x<=24;x+=6){this.scene.add(box(.3,20,.4,M.steel,x,6,-20.5),box(.14,.12,32,M.steel,x,15,-4));const strip=new T.MeshBasicMaterial({color:0x80ffbc});this.scene.add(box(.06,8,.04,strip,x,6,-20.2));}
 const logo=sign('SUJA / STACK DIVISION',14,2.1);logo.position.set(0,5,-20.6);this.scene.add(logo);
 for(const side of [-1,1]){for(let i=0;i<4;i++){const p=pallet(3.7);p.position.set(side*(11+i%2*4.6),-2.7,-10+Math.floor(i/2)*7);this.scene.add(p);for(let j=0;j<6;j++){const c=box(1.2,.75,.85,M.kraft);c.position.set(p.position.x+(j%3-1)*1.2,-2.2+Math.floor(j/3)*.8,p.position.z);this.scene.add(c);}}
 const belt=box(2,.3,18,M.dark,side*9,-.3,-5);this.scene.add(belt);for(let j=0;j<8;j++)this.scene.add(box(1.4,.8,1.1,M.kraft,side*9,.2,-12+j*2));}
 this.machine=new T.Group();this.machine.position.set(0,0,-11);this.machine.add(box(3.1,3,1.7,M.green,0,1,0,true),box(3.3,.18,1.9,M.steel,0,2.57,0),box(1.8,1.1,.04,M.dark,0,1.4,.86));const machineSign=sign('LABEL / ROUTE',2.7,.5);machineSign.position.set(0,2.1,.89);this.machine.add(machineSign);this.scene.add(this.machine);this.scanner=box(1.5,.035,.06,new T.MeshBasicMaterial({color:0xbaff72}),0,1.7,-9.3);this.scene.add(this.scanner);
 this.line=new T.Group();this.scene.add(this.line);this.palletRoot=new T.Group();this.scene.add(this.palletRoot);this.ghosts=new T.Group();this.scene.add(this.ghosts);this.arrowMat=new T.MeshBasicMaterial({color:0xd1ff91});
 }
 setup(s){this.level=s.level;this.lanes=s.lanes;this.line.clear();this.palletRoot.clear();this.ghosts.clear();for(const m of this.live.values())this.scene.remove(m);this.live.clear();this.placed=[];this.placedCount=0;const width=s.lanes*1.85;
 this.line.add(box(width+.25,.26,14.4,M.dark,0,1.3,-2.2,true));const rollGeo=new T.CylinderGeometry(.075,.075,width-.08,12),rollers=new T.InstancedMesh(rollGeo,M.steel,66);const o=new T.Object3D();for(let i=0;i<66;i++){o.position.set(0,1.51,-9.22+i*.214);o.rotation.z=Math.PI/2;o.updateMatrix();rollers.setMatrixAt(i,o.matrix);}rollers.receiveShadow=true;this.line.add(rollers);
 for(let lane=0;lane<s.lanes;lane++){const x=laneX(lane,s.lanes);for(const side of [-1,1])this.line.add(box(.035,.018,13.8,new T.MeshBasicMaterial({color:side===1?0x537f73:0x134b41}),x+side*.9,1.62,-2.1));
 const zone=box(1.7,.016,3.4,new T.MeshBasicMaterial({color:0x8355b2,transparent:true,opacity:.42}),x,1.62,2.96);this.line.add(zone);const n=sign(String(lane+1),.5,.48);n.rotation.x=-Math.PI/2;n.position.set(x,1.66,4.5);this.line.add(n);
 for(let row=0;row<2;row++){const target=targetTurn(lane,row,s.lanes),g=new T.Group();g.position.set(x,1.55,6+row*1.5);const shape=outline();shape.rotation.y=target*Math.PI/2;g.add(shape);const a=sign('↓',.48,.48);a.rotation.set(-Math.PI/2,0,0);a.position.y=.04;const ag=new T.Group();ag.rotation.y=target*Math.PI/2;ag.add(a);g.add(ag);g.userData={lane,row};this.ghosts.add(g);}}
 this.line.add(box(.06,.08,14.5,new T.MeshBasicMaterial({color:0xa6f972}),-width/2,1.48,-2.1),box(.06,.08,14.5,new T.MeshBasicMaterial({color:0x9a72e6}),width/2,1.48,-2.1));
 this.palletRoot.add(pallet(width+.2));this.palletRoot.position.set(0,1.1,6.75);this.resize();
 }
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);const aspect=w/h,width=(this.lanes||3)*1.85+3.1;const viewH=Math.max(20,width/aspect);this.camera.left=-viewH*aspect/2;this.camera.right=viewH*aspect/2;this.camera.top=viewH/2;this.camera.bottom=-viewH/2;this.camera.updateProjectionMatrix();this.setView(this.view);}
 setView(view){this.view=view;this.camera.position.set(view==='angle'?6:0,view==='overhead'?30:23,view==='overhead'?2:22);this.camera.lookAt(0,0,-1.5);this.camera.updateMatrixWorld();}
 pick(x,y){const r=this.canvas.getBoundingClientRect();this.pointer.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects([...this.live.values()],true);if(hits.length)return hits[0].object.userData.id;
 let id=null,dist=30;for(const [key,m]of this.live){if(m.userData.progress<.22)continue;const p=m.position.clone().add(new T.Vector3(0,.45,0)).project(this.camera);const d=Math.hypot((p.x+1)/2*r.width+r.left-x,(1-p.y)/2*r.height+r.top-y);if(d<dist){dist=d;id=key;}}return id;}
 makeCase(b){const m=new T.Group();m.add(this.template.clone());const ring=outline(1.42,1.05,0xc195ff);ring.position.y=.01;ring.rotation.y=b.target*Math.PI/2;m.add(ring);m.userData.ring=ring;m.traverse(o=>o.userData.id=b.id);return m;}
 event(e){if(e.type==='stack'||e.type==='miss'){const m=this.live.get(e.box.id);if(m){this.live.delete(e.box.id);this.flights.push({m,box:e.box,miss:e.type==='miss',age:0,start:m.position.clone()});}if(e.type==='stack')this.burst(laneX(e.box.lane,this.lanes),1.6,5.2,e.timed?0xc8a2ff:0xadff91);}if(e.type==='layer'||e.type==='pallet')this.burst(0,2,6,0xf3da76,45);}
 burst(x,y,z,color,count=13){for(let i=0;i<count;i++){const m=box(.08,.08,.08,new T.MeshBasicMaterial({color}),x,y,z);this.scene.add(m);this.fx.push({m,age:0,v:new T.Vector3((Math.random()-.5)*4,2+Math.random()*4,(Math.random()-.5)*3)});}}
 render(s,dt){if(s!==this.sim){this.level=-1;for(const f of this.flights)this.scene.remove(f.m);this.flights=[];this.sim=s;}if(s.level!==this.level)this.setup(s);this.clock+=dt;this.scanner.position.y=1.5+Math.sin(this.clock*6)*.3;
 this.palletRoot.position.y=T.MathUtils.lerp(this.palletRoot.position.y,1.1-s.layer*.82,Math.min(1,dt*4));
 for(const b of s.boxes){let m=this.live.get(b.id);if(!m){m=this.makeCase(b);this.scene.add(m);this.live.set(b.id,m);m.children[0].rotation.y=b.turn*Math.PI/2;}m.position.copy(pathPosition(b,s.lanes));m.getObjectByName('ShippingLabel').visible=b.progress>=.12;m.children[0].rotation.y=T.MathUtils.lerp(m.children[0].rotation.y,b.turn*Math.PI/2,Math.min(1,dt*19));m.userData.progress=b.progress;const valid=alignment(b.turn,b.target);m.userData.ring.material.color.setHex(mod4(b.turn)===b.target?0xbaff78:valid?0xffbf6b:0xb787ff);m.userData.ring.material.opacity=b.progress>=.22?.65+.25*Math.sin(this.clock*5):0;}
 for(const [id,m]of this.live)if(!s.boxes.some(b=>b.id===id)){this.scene.remove(m);this.live.delete(id);}
 while(this.placedCount<s.placed.length){const b=s.placed[this.placedCount++],m=this.template.clone();m.position.set(laneX(b.lane,s.lanes),.38+b.layer*.82,(b.row-.5)*1.5);m.rotation.y=mod4(b.turn)*Math.PI/2;m.visible=false;m.userData.id=b.id;this.palletRoot.add(m);this.placed.push(m);}
 for(const f of this.flights){f.age+=dt;const t=Math.min(1,f.age/.52);if(f.miss){f.m.position.set(f.start.x+(f.box.lane%2?1:-1)*t*.5,1.6-5*t*t,5+2*t);f.m.rotation.z=t*2;f.m.rotation.x=t*1.5;}else{f.m.position.lerpVectors(f.start,new T.Vector3(laneX(f.box.lane,s.lanes),1.48,6+f.box.row*1.5),t);f.m.position.y+=Math.sin(t*Math.PI)*.45;}if(t>=1){this.scene.remove(f.m);const placed=this.placed.find(m=>m.userData.id===f.box.id);if(placed)placed.visible=true;}}
 this.flights=this.flights.filter(f=>f.age<.52);for(const m of this.placed)if(!this.flights.some(f=>f.box.id===m.userData.id))m.visible=true;
 for(const g of this.ghosts.children){const filled=s.slots.includes(g.userData.lane+':'+g.userData.row);g.visible=!filled;g.children[0].material.opacity=.5+.3*Math.sin(this.clock*3);}
 for(const f of this.fx){f.age+=dt;f.m.position.addScaledVector(f.v,dt);f.v.y-=6*dt;f.m.rotation.z+=dt*4;f.m.scale.setScalar(Math.max(0,1-f.age));if(f.age>1)this.scene.remove(f.m);}this.fx=this.fx.filter(f=>f.age<1);
 this.renderer.render(this.scene,this.camera);}
}
